.PHONY: install install-dev test lint format readme clean help

PYTHON ?= python

help:
	@echo "install     install pinned runtime dependencies"
	@echo "test        run the unit tests (seconds, no GPU, no data needed)"
	@echo "lint        ruff check src/ tests/"
	@echo "format      ruff format src/ tests/"
	@echo "readme      regenerate the README result tables from outputs/results.json"
	@echo "clean       remove caches and build artefacts (keeps data/ and outputs/)"

install:
	$(PYTHON) -m pip install -r requirements.txt

install-dev: install
	$(PYTHON) -m pip install pytest ruff

# The tests import from src/ via tests/conftest.py, so no install step is needed.
test:
	$(PYTHON) -m pytest tests -q

lint:
	$(PYTHON) -m ruff check src tests

format:
	$(PYTHON) -m ruff format src tests

# Rewrites the tables between the AUTOGENERATED markers in README.md from
# outputs/results.json. No number in the README is ever typed by hand.
readme:
	$(PYTHON) scripts/update_readme.py

clean:
	$(PYTHON) -c "import shutil, pathlib; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]"
	$(PYTHON) -c "import shutil, pathlib; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('.ipynb_checkpoints')]"
	$(PYTHON) -c "import shutil; shutil.rmtree('.pytest_cache', ignore_errors=True); shutil.rmtree('.ruff_cache', ignore_errors=True)"
