"""Regenerate the README's result tables from outputs/results.json.

Run with `make readme`. Every number in the README comes from this script, so
the README cannot drift from what was actually executed — and if the notebooks
have not been run yet, the tables say exactly that instead of showing numbers
nobody produced.

Content between a pair of markers is replaced:

    <!-- AUTOGENERATED:<name> -->
    ...replaced...
    <!-- END:<name> -->
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from s2map import evaluate as E  # noqa: E402

README = ROOT / "README.md"
PLACEHOLDER = (
    "_No results recorded yet. Run the notebooks — each one appends to "
    "`outputs/results.json` — then `make readme`._"
)


def results_section(results: list[dict]) -> str:
    if not results:
        return PLACEHOLDER
    # `_ceiling` duplicates arm2_resnet18_13band under a different name — it exists
    # so NB04 can look up one number, not as a separate experiment. Any arm whose
    # name starts with "_" is bookkeeping and is kept out of the public table.
    rows = [r for r in results if not str(r.get("arm", "")).startswith("_")]

    # Chapter 07 re-ran the two NB02 ablations at 3 seeds. Those measurements
    # supersede the single-seed rows, so the table shows the better ones —
    # rendered from the NB07 entry rather than copied into results.json, so the
    # ledger keeps exactly one record of each measurement.
    verification = next((r for r in results if r.get("arm") == "verification"), None)
    if verification:
        labels = {
            "resnet18_rgb": ("RGB only", "3 seeds (NB07) — supersedes the NB02 single-seed run"),
            "resnet18_randomstem": ("13-band", "3 seeds (NB07) — pretrained stem discarded"),
        }
        superseded = {f"arm2_{k}" for k in labels}
        rows = [r for r in rows if r.get("arm") not in superseded]
        for arm, stats in (verification.get("ablations_3_seed") or {}).items():
            name, note = labels.get(arm, (arm, "3 seeds (NB07)"))
            rows.append({
                "notebook": "02", "arm": f"arm2_{arm}", "input": name,
                "test_macro_f1": stats, "notes": note,
            })
    return E.results_table(rows, notebooks={"02", "03"})


def label_efficiency_section(results: list[dict]) -> str:
    entry = next((r for r in results if r.get("arm") == "label_efficiency_sweep"), None)
    if entry is None:
        return PLACEHOLDER

    curves = entry.get("curves", {})
    k_values = entry.get("k_values", [])
    lines = ["| Frozen encoder | " + " | ".join(f"k={k}" for k in k_values) + " |"]
    lines.append("|---" * (len(k_values) + 1) + "|")
    for name, curve in curves.items():
        tag = " *(reference — saw all labels)*" if curve.get("reference") else ""
        cells = [f"{m:.3f} ± {s:.3f}" for m, s in zip(curve["mean"], curve["std"])]
        lines.append(f"| {name}{tag} | " + " | ".join(cells) + " |")

    extras = []
    if entry.get("supervised_ceiling_macro_f1") is not None:
        extras.append(
            f"Full-supervision ceiling (all {'18,900'} training labels): "
            f"**{entry['supervised_ceiling_macro_f1']:.3f}** macro-F1."
        )
    for name, value in (entry.get("zero_shot_anchors") or {}).items():
        extras.append(f"{name} zero-shot (0 labels): **{value:.3f}** macro-F1.")
    if entry.get("crossover_k_finetune_beats_probe"):
        extras.append(
            f"Fine-tuning overtakes every frozen probe at roughly "
            f"**k = {entry['crossover_k_finetune_beats_probe']}** labels per class."
        )
    return "\n".join(lines) + ("\n\n" + "  \n".join(extras) if extras else "")


def scene_section(results: list[dict]) -> str:
    entry = next((r for r in results if r.get("arm") == "scene_inference"), None)
    if entry is None:
        return PLACEHOLDER
    lines = [
        f"Scene: `{entry.get('item_id')}` over {entry.get('aoi')}, "
        f"{str(entry.get('scene_datetime'))[:10]}, {entry.get('cloud_cover')}% cloud.",
        "",
        "| Class | Predicted area (ha) |",
        "|---|---|",
    ]
    for name, ha in (entry.get("areas_hectares") or {}).items():
        lines.append(f"| {name} | {ha:,.0f} |")
    if entry.get("normalisation_disagreement") is not None:
        lines += [
            "",
            f"The two normalisation choices (training statistics vs scene statistics) "
            f"disagree on **{entry['normalisation_disagreement']:.1%}** of valid pixels — "
            "identical weights, identical pixels, different preprocessing. That is the "
            "L1C→L2A domain shift, measured.",
        ]
    return "\n".join(lines)


SECTIONS = {
    "results": results_section,
    "label_efficiency": label_efficiency_section,
    "scene": scene_section,
}


def main() -> int:
    results = E.load_results()
    text = README.read_text(encoding="utf-8")
    for name, builder in SECTIONS.items():
        pattern = re.compile(
            rf"(<!-- AUTOGENERATED:{name} -->\n).*?(\n<!-- END:{name} -->)", re.DOTALL
        )
        if not pattern.search(text):
            print(f"warning: no markers for section {name!r} in README.md")
            continue
        body = builder(results)  # evaluated before sub, so the closure below is safe
        text = pattern.sub(lambda m, body=body: m.group(1) + body + m.group(2), text)
    README.write_text(text, encoding="utf-8")
    print(f"updated {README} from {len(results)} recorded result entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
