"""Regenerate the README's result tables from outputs/results.json.

Run with `make readme`. Every number in the README comes from this script, so
the README cannot drift from what was actually executed — and if the notebooks
have not been run yet, the tables say exactly that instead of showing numbers
nobody produced.

Content between a pair of markers is replaced:

    <!-- AUTOGENERATED:<name> -->
    ...replaced...
    <!-- END:<name> -->
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from s2map import evaluate as E  # noqa: E402

README = ROOT / "README.md"
PLACEHOLDER = (
    "_No results recorded yet. Run the notebooks — each one appends to "
    "`outputs/results.json` — then `make readme`._"
)


def _index(results: list[dict]) -> dict:
    return {(r.get("notebook"), r.get("arm")): r for r in results}


def _f1(entry: dict | None) -> str:
    if entry is None:
        return "—"
    v = entry.get("test_macro_f1")
    if isinstance(v, dict):
        return f"{v['mean']:.3f} ± {v['std']:.3f}"
    return f"{v:.3f}" if isinstance(v, float) else "—"


def headline_table(results: list[dict]) -> str:
    """One table telling the whole story, ordered by how many labels were used.

    Deliberately not a dump of results.json: the point of this project is the
    trade between labels and performance, so the table is grouped by labelling
    budget rather than by notebook.
    """
    if not results:
        return PLACEHOLDER
    idx = _index(results)
    ver = idx.get(("07", "verification"))
    sweep = idx.get(("04", "label_efficiency_sweep"))

    rows: list[tuple[str, str, str, str, str]] = []

    # --- zero-shot -----------------------------------------------------------
    if ver:
        best = ver.get("best_strategy_per_model", {})
        prompts = ver.get("prompt_sweep", {})
        for model in ("CLIP", "RemoteCLIP"):
            key = f"{model}|{best.get(model)}"
            if key in prompts:
                label = "CLIP ViT-B/32" if model == "CLIP" else "RemoteCLIP ViT-B/32"
                rows.append(("zero", f"{label} — zero-shot", "RGB (3 of 13 bands)", "**0**",
                             f"{prompts[key]['macro_f1']:.3f}"))

    # --- few-shot ------------------------------------------------------------
    if sweep:
        curves = sweep.get("curves", {})
        probes = {n: c for n, c in curves.items() if not c.get("reference")}
        for k in (1, 10, 100):
            best_name, best_mean, best_std = None, -1.0, 0.0
            for name, c in probes.items():
                if "Fine-tuned" in name or k not in c["k"]:
                    continue
                i = c["k"].index(k)
                if c["mean"][i] > best_mean:
                    best_name, best_mean, best_std = name, c["mean"][i], c["std"][i]
            if best_name:
                rows.append(("few", f"Linear probe on frozen {best_name}", "RGB (3 of 13 bands)",
                             f"{k} / class ({k * 10:,})", f"{best_mean:.3f} ± {best_std:.3f}"))
        ft = curves.get("Fine-tuned ResNet-18 (RGB)")
        if ft and 100 in ft["k"]:
            i = ft["k"].index(100)
            rows.append(("few", "Fine-tuned ResNet-18", "RGB (3 of 13 bands)", "100 / class (1,000)",
                         f"{ft['mean'][i]:.3f} ± {ft['std'][i]:.3f}"))

    # --- full supervision ----------------------------------------------------
    full = "18,900"
    supervised = [
        ("arm0_random_forest", "Random Forest on 29 spectral statistics", "13-band summary stats"),
        ("arm1_small_cnn", "Small CNN, trained from scratch", "13-band"),
        ("arm2_resnet18_rgb", "ResNet-18, ImageNet-pretrained", "RGB (3 of 13 bands)"),
        ("arm3_vit_small", "ViT-S/16, ImageNet-pretrained", "13-band"),
        ("arm2_resnet18_13band", "**ResNet-18, ImageNet-pretrained, inflated stem**", "**13-band**"),
    ]
    for arm, label, inp in supervised:
        entry = idx.get(("02", arm))
        # The RGB ablation was re-run at 3 seeds in NB07; prefer that measurement.
        if arm == "arm2_resnet18_rgb" and ver and ver.get("ablations_3_seed", {}).get("resnet18_rgb"):
            s = ver["ablations_3_seed"]["resnet18_rgb"]
            value = f"{s['mean']:.3f} ± {s['std']:.3f}"
        else:
            value = _f1(entry)
        bold = arm == "arm2_resnet18_13band"
        rows.append(("sup", label, inp, f"**{full}**" if bold else full,
                     f"**{value}**" if bold else value))

    header = [
        "| Approach | Input | Labels used | Test macro-F1 |",
        "|:---|:---|---:|---:|",
    ]
    group_titles = {
        "zero": "| **No labels** | | | |",
        "few": "| **A handful of labels** | | | |",
        "sup": "| **Full supervision** | | | |",
    }
    out, seen = header, set()
    for group, label, inp, labels, value in rows:
        if group not in seen:
            out.append(group_titles[group])
            seen.add(group)
        out.append(f"| {label} | {inp} | {labels} | {value} |")

    # --- the honesty row -----------------------------------------------------
    if ver and ver.get("split_comparison"):
        blocked = next((v for k, v in ver["split_comparison"].items() if "blocked" in k), None)
        if blocked:
            out.append("| **Corrected for leakage** | | | |")
            out.append(
                f"| Same ResNet-18, scene-blocked split | 13-band | {full} | "
                f"{blocked['macro_f1']:.3f} |"
            )
    return "\n".join(out)


def label_efficiency_section(results: list[dict]) -> str:
    entry = next((r for r in results if r.get("arm") == "label_efficiency_sweep"), None)
    if entry is None:
        return PLACEHOLDER
    curves, k_values = entry.get("curves", {}), entry.get("k_values", [])
    lines = ["| Frozen encoder | " + " | ".join(f"**k={k}**" for k in k_values) + " |"]
    lines.append("|:---" + "|---:" * len(k_values) + "|")
    for name, curve in curves.items():
        if curve.get("reference"):
            continue
        cells = [f"{m:.3f}" for m in curve["mean"]]
        if len(cells) < len(k_values):  # the fine-tuning arm ran at a subset of k
            cells = [f"{curve['mean'][curve['k'].index(k)]:.3f}" if k in curve["k"] else "—"
                     for k in k_values]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(lines)


def scene_section(results: list[dict]) -> str:
    entry = next((r for r in results if r.get("arm") == "scene_inference"), None)
    if entry is None:
        return PLACEHOLDER
    areas = entry.get("areas_hectares") or {}
    top = sorted(((k, v) for k, v in areas.items() if not k.startswith("_")),
                 key=lambda kv: -kv[1])[:4]
    parts = ", ".join(f"{name} {ha:,.0f} ha" for name, ha in top)
    return (
        f"Scene `{entry.get('item_id')}` — {str(entry.get('scene_datetime'))[:10]}, "
        f"{entry.get('cloud_cover'):.2f} % cloud. Largest predicted classes: {parts}. "
        f"The two defensible normalisation choices disagree on "
        f"**{entry.get('normalisation_disagreement', 0):.1%}** of valid pixels."
    )


SECTIONS = {
    "headline": headline_table,
    "label_efficiency": label_efficiency_section,
    "scene": scene_section,
}


def main() -> int:
    results = E.load_results()
    text = README.read_text(encoding="utf-8")
    for name, builder in SECTIONS.items():
        pattern = re.compile(
            rf"(<!-- AUTOGENERATED:{name} -->\n).*?(\n<!-- END:{name} -->)", re.DOTALL
        )
        if not pattern.search(text):
            print(f"warning: no markers for section {name!r} in README.md")
            continue
        body = builder(results)
        text = pattern.sub(lambda m, body=body: m.group(1) + body + m.group(2), text)
    README.write_text(text, encoding="utf-8")
    print(f"updated {README} from {len(results)} recorded result entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
